"""add_cv_sections_to_users

Revision ID: 59e6ceb46aeb
Revises: 2031f3d10fe2
Create Date: 2025-12-07 18:45:38.676845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e6ceb46aeb'
down_revision = '2031f3d10fe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cv_personal_info', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_technical_skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_soft_skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_projects', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_education', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cv_awards', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cv_awards')
    op.drop_column('users', 'cv_education')
    op.drop_column('users', 'cv_projects')
    op.drop_column('users', 'cv_experience')
    op.drop_column('users', 'cv_soft_skills')
    op.drop_column('users', 'cv_technical_skills')
    op.drop_column('users', 'cv_summary')
    op.drop_column('users', 'cv_personal_info')
    # ### end Alembic commands ###
