"""Initial migration - create all tables

Revision ID: df33a7fb1531
Revises: 
Create Date: 2025-12-02 21:07:05.032428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df33a7fb1531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_company'), 'job_offers', ['company'], unique=False)
    op.create_index('ix_job_offers_company_title', 'job_offers', ['company', 'title'], unique=False)
    op.create_index('ix_job_offers_created_at', 'job_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_offers_id'), 'job_offers', ['id'], unique=False)
    op.create_index(op.f('ix_job_offers_title'), 'job_offers', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('application_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter_text', sa.Text(), nullable=True),
    sa.Column('cover_letter_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_drafts_id'), 'application_drafts', ['id'], unique=False)
    op.create_index('ix_application_drafts_job_offer_id', 'application_drafts', ['job_offer_id'], unique=False)
    op.create_index('ix_application_drafts_status', 'application_drafts', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('portal_type', sa.String(length=50), nullable=True),
    sa.Column('submitted_by', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('confirmation_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index('ix_applications_job_offer_id', 'applications', ['job_offer_id'], unique=False)
    op.create_index('ix_applications_next_action_date', 'applications', ['next_action_date'], unique=False)
    op.create_index('ix_applications_sent_at', 'applications', ['sent_at'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('skills_detected', sa.Text(), nullable=True),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.create_index('ix_job_matches_job_offer_id', 'job_matches', ['job_offer_id'], unique=False)
    op.create_index('ix_job_matches_score', 'job_matches', ['score'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_application_id', 'timeline_events', ['application_id'], unique=False)
    op.create_index('ix_timeline_events_event_date', 'timeline_events', ['event_date'], unique=False)
    op.create_index('ix_timeline_events_event_type', 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_event_type', table_name='timeline_events')
    op.drop_index('ix_timeline_events_event_date', table_name='timeline_events')
    op.drop_index('ix_timeline_events_application_id', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_job_matches_score', table_name='job_matches')
    op.drop_index('ix_job_matches_job_offer_id', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_sent_at', table_name='applications')
    op.drop_index('ix_applications_next_action_date', table_name='applications')
    op.drop_index('ix_applications_job_offer_id', table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_application_drafts_status', table_name='application_drafts')
    op.drop_index('ix_application_drafts_job_offer_id', table_name='application_drafts')
    op.drop_index(op.f('ix_application_drafts_id'), table_name='application_drafts')
    op.drop_table('application_drafts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_offers_title'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_id'), table_name='job_offers')
    op.drop_index('ix_job_offers_created_at', table_name='job_offers')
    op.drop_index('ix_job_offers_company_title', table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_company'), table_name='job_offers')
    op.drop_table('job_offers')
    # ### end Alembic commands ###
